spring:
  datasource:
    url: jdbc:mysql://localhost:3306/faq  # 데이터베이스 URL
    username: root                       # MySQL 사용자명
    password: biday              # MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update                   # 테이블 생성/수정
    show-sql: true                       # 콘솔에 쿼리 출력 여부
    properties:
      hibernate:
        format_sql: true                 # 출력되는 SQL을 포맷할지 여부

springdoc:
  swagger-ui:
    path: /swagger-ui.html               # Swagger UI 경로
    operationsSorter: method             # Swagger에서 메서드 정렬 방식 (기본값)
    display-request-duration: true       # 요청 처리 시간 표시 여부
    enable: true                         # Swagger UI 활성화 여부
  api-docs:
    path: /v3/api-docs                   # API 문서 경로 (기본값은 `/v3/api-docs`)

logging:
  level:
    org.hibernate.SQL: DEBUG             # SQL 출력 설정
    org.hibernate.type.descriptor.sql: TRACE  # 파라미터 바인딩 출력